### ISSUE TITLE
Make sure installtool.exe executes from within the it's location

### ISSUE THREAD

**Issue by Sarafian** [Sarafian/ISHBootstrap#73]
InstallTool.exe on Content Manager 13 has switched to NLOG loggin. Currently, there is an issue and the file doesn't know where to log when it's executed like 'C:\CDPath\__Install\InstallTool.exe`. 

**Log from packer against amazon ebs**
```text
 amazon-ebs: STEP 12: Saving the information into the history (registry and folder)
    amazon-ebs: ===============================================================================
    amazon-ebs: Object reference not set to an instance of an object.
    amazon-ebs: An unexpected system failure occurred: Object reference not set to an instance of an object.
    amazon-ebs:
    amazon-ebs: InstallTool.SystemFailureException: An unexpected system failure occurred: Object reference not set to an inst             ance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
    amazon-ebs: at Trisoft.Setup.History.HistoryObject.set_LogFile(FileObject value)
    amazon-ebs: at InstallTool.InstallHistory.End(VersionHistoryStatus versionHistoryStatus, FileObject logFile)
    amazon-ebs: at InstallTool.Install.End()
    amazon-ebs: --- End of inner exception stack trace ---
    amazon-ebs: at InstallTool.Install.End()
    amazon-ebs: at InstallTool.InstallTool.Install()
    amazon-ebs: at InstallTool.InstallTool.Main(String[] args)
    amazon-ebs: SystemFailureException message: An unexpected system failure occurred: Object reference not set to an instance              of an object.
    amazon-ebs: SystemFailureException parameters: [reason=Object reference not set to an instance of an object.]
    amazon-ebs: InnerException: Object reference not set to an instance of an object.
    amazon-ebs:
    amazon-ebs: InstallTool.Main
    amazon-ebs: MAIN ERROR: An unexpected system failure occurred: Object reference not set to an instance of an object.
    amazon-ebs:
    amazon-ebs: [Installing InfoShare] Finish local
    amazon-ebs: [End Script] C:\Provision\ISHBootstrap\Source\Server\Install\Install-ISHDeployment.ps1
```

The team suggests to make sure that the current location is 'C:\CDPath\__Install\` before executing.

**Comment by Sarafian** [comment]
This is a temporary fix until internal **TS-12532** is fixed. Code is marked in region `Workaround GH-73`
